### ISSUE TITLE
Which version of Python to use to run this?

### ISSUE THREAD

**Issue by bv42** [octoenergy/oejp-api-example#3]
hi, 
first, thank you for sharing this API example. I am a customer of OEJP and very eager to try this out. 
However, I am somewhat lagging on the recent python versions and have issues getting this example to run. 

Specifically I tried with Python 3.8 and 3.9 : both break on line 24 of local.py. 
Am I correct to assume that this is some new syntax which was introduced in Python 3.10 or 3.11?

Would it be possible to add some note to the readme file regarding which version of Python should be used to run this?

```
 oejp-api-example git:(main) uvicorn main:app --reload                                                      
INFO:     Will watch for changes in these directories: ['/src/oejp-api-example']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [178870] using WatchFiles
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bv42/.local/lib/python3.8/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/bv42/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/bv42/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/bv42/.local/lib/python3.8/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/bv42/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/src/oejp-api-example/./main.py", line 6, in <module>
    import localtime
  File "/src/oejp-api-example/./localtime.py", line 24, in <module>
    def midnight(date_: datetime.date | None = None) -> datetime.datetime:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'


```

**Comment by girisagar46** [comment]
Thank you for reporting. It should be fixed now. :)
